# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_BCMDHD)	+= rkwifi/
obj-$(CONFIG_CYW_BCMDHD)	+= cywdhd/
obj-$(CONFIG_INFINEON_DHD)	+= infineon/
obj-$(CONFIG_RTL8733BS) += rtl8733bs/
obj-$(CONFIG_AIC8800DC) += aic8800dc/
