# SPDX-License-Identifier: GPL-2.0-or-later

obj-$(CONFIG_ROCKCHIP_AMP_IMU) += rk-amp-imu.o
rk-amp-imu-$(CONFIG_ROCKCHIP_AMP_IMU) += rk_amp_imu_core.o
rk-amp-imu-$(CONFIG_ROCKCHIP_AMP_IMU) += rk_amp_imu_trigger.o
